require_relative "./top_books/version.rb"
require_relative "./top_books/cli.rb"
require_relative "./top_books/books.rb"
require_relative "./top_books/amazonScraper.rb"
require_relative "./top_books/bookScraper.rb"
require_relative "./top_books/more.rb"
require_relative "./top_books/years.rb"
